
import woman from './pic-collage/woman.jpg';
import womanmap from './pic-collage/woman-map.jpg';
import map from './pic-collage/map2.jpg';
import margarita from './pic-collage/margarita.jpg';
import volcano from './pic-collage/volcano.jpg';
import cotopaxi2 from './pic-collage/cotopaxi2.jpg';
import llama from './pic-collage/llama.jpeg';
import cowboy from './pic-collage/cowboy.jpg';
import ncowboy from './pic-collage/no-cowboy.jpg';
import godess from './pic-collage/godess.jpg';
import helperbg from './pic-collage/helper-bg.jpg';
import helper from './pic-collage/helper.jpg';
import lionring from './pic-collage/lion-ring.jpg';
import map2 from './pic-collage/map2.jpg';
import ringhelper from './pic-collage/ring-helper.jpg';
import ring from './pic-collage/ring.jpg';
import earrings from './pic-collage/earrings.jpg';
import cliff from './pic-collage/cliff2.jpeg';
import ceibo from './pic-collage/ceibo.jpg';
import king from './pic-collage/king.jpg';
import shore from './pic-collage/rocky-shore2.jpg';



const Content = [

  { id:0,
    title: 'xx Welcome xx',
    image1: volcano,
    image2: woman,
    copyposition: '  col-md-offset-4 col-md-4 top-5',
    image1position: ' col-md-offset-0 col-md-5',
    image2position: ' col-md-offset-2 col-md-4 top-10',
    copy: 'You traveled back thousands of years to find a ring that will save your family.',
    copy2:'Waking up on an active volcano, you quickly get up knowing you have 24h to find the ring.',
    button1copy:"Look around",
    button2copy:"Find help",
    choice1:1,
    choice2:2,
  },
    /// A
  { id:1,
    title: 'The Land',
    image1: map,
    image2: llama,
    image1position: ' col-md-offset-1 col-md-6 top-5',
    image2position: ' col-md-offset-0 col-md-2 top-1',
    copyposition: '  col-md-offset-6 col-md-4 top-20',
    copy: 'You run, quicker than you ever have before, past mountains, llamas and rivers.',
    copy2:' Finally you reach the shore, when a sturdy figure emerges from the water.',
    button1copy:"Meet them",
    button2copy:"Hide",
    choice1:3,
    choice2:4,
  },
  { id:2,
    title: 'The Cowboy',
    image1: cotopaxi2,
    image2: cowboy,
    image1position: ' col-md-offset-1 col-md-3 top-20',
    image2position: ' col-md-6 top-0',
    copyposition: '  col-md-offset-2 col-md-4 top-10',
    copy: 'You yell in to the void. After a few minutes, you hear a horse riding towards you. A well dressed man steps off,',
    copy2:'"I was waiting for you. Jump on, and I will take you to the ring."',
    button1copy:"Kick him",
    button2copy:"Jump on",
    choice1:5,
    choice2:6,
  },
    /// B - Helper
    { id:3,
      title: 'The Amiga',
      image1: helper,
      image2: earrings,
      image1position: ' col-md-offset-0 col-md-5 top-0',
      image2position: ' col-md-offset-0 col-md-3 top-20',
      copyposition: '  col-md-offset-7 top-0 col-md-4',
      copy: '“Hello, I’ve been sent here by your abuelo”. I’ll help you find the ring you’re looking for.',
      copy2:'She extends her hand to show a pair of sparkling earrings, “Trust me”.',
      button1copy:"Accept them",
      button2copy:"Knock them down",
      choice1:7,
      choice2:8,
    },
    { id:4,
      title: 'The Earrings',
      image1: ceibo,
      image2: earrings,
      image1position: ' col-md-offset-0 col-md-3 top-5',
      image2position: ' col-md-offset-3 col-md-5 top-0',
      copyposition: '  col-md-offset-2 col-md-4 top-10',
      copy: 'As you duck behind a palo santo tree, you spot something bright on the ground.',
      copy2:'You hesitate but decide to pick it up and find a beautiful pair of silver earrings, and hold them in your hand for a moment',
      choice1:9,
      choice2:10,
      button1copy:"Pocket them",
      button2copy:"Leave them behind",
    },
    /// B - Cowboy
    { id:5,
      title: 'The earrings',
      image1: ncowboy,
      image2: womanmap,
      image1position: ' col-md-offset-3 col-md-4 top-10',
      image2position: ' col-md-4 top-10',
      copyposition: '  col-md-offset-1 col-md-4 top-5',
      copy: ' Riding swfitly through a dry jungle, something shiny catches your eye.',
      copy2:' You suddenly stop the horse and pick up a pair of earrings from the ground.',
      button1copy: 'Pocket them',
      button2copy: 'Wear them',
      choice1: '11',
      choice2: '12',
    },
  { id:6,
    title: 'The earrings',
    image1: cliff,
    image2: earrings,
    image1position: ' col-md-offset-0 col-md-3 top-20',
    image2position: ' col-md-offset-2 col-md-5 top-10',
    copyposition: '  col-md-offset-2 col-md-4 top-5',
    copy: 'Youve been riding for a few minutes when you come to the edge of a cliff, the cowboy turns to you and asks you for your hand in exchange of a pair of beautiful earrings',
    button1copy: 'Steal the earrings',
    button2copy: 'Reject him',
    choice1: '13',
    choice2: '14',
  },
  //
  { id:7,
    title: 'The Cliff',
    image1: godess,
    image2: cliff,
    image1position: ' col-md-offset-0 col-md-5 top-0',
    image2position: ' col-md-offset-2 col-md-3 top-5"',
    copyposition: '  top-10 col-md-offset-5 col-md-4',
    copy: 'Earrings dangling, you walk through dry terrains with your amiga holding your hand. Here, she slowly transforms into a different figure. She asks you to trust her and to jump off to find the jewel. ',
    copy2:'In a fit of emotions and urgency you…',
    button1copy: 'Jump off',
    button2copy: 'Begin to weep',
    choice1: '15',
    choice2: '17',
  },
  { id:8,
    title: 'The Cliff',
    image1: cliff,
    image2: godess,
    image1position: ' col-md-offset-3 col-md-4 top-5',
    image2position: ' pic-item col-md-4 top-10',
    copyposition: '  top-10 col-md-offset-1 col-md-4',
    copy: 'All she says is, “You’ll regret that”, before she disappears into a forest of Ceibos. You’re alone again, and slowly make your way back to the sea till you reach a cliff. A figure appears at the edge of the cliff. ',
    copy2:'In a fit of emotions and urgency you…',
    button1copy: 'Begin to weep',
    button2copy: 'Push her off',
    choice1: '15',
    choice2: '16',
  },
  { id:9,
    title: 'The Cliff',
    image1: cliff,
    image2: king,
    image1position: ' col-md-offset-3 col-md-3 top-15',
    image2position: ' col-md-5 col-md-offset-0 top-0',
    copyposition: '  col-md-offset-0  top-0 col-md-4',
    copy: 'Strangely untroubled, you make your way to the sea under a dense blue sky and quiet murmur of birds. You reach a cliff where someone approaches you and whispers in your ear: jump with me. ',
    copy2:'In a fit of emotions and urgency you…',
    button1copy: 'Begin to weep',
    button2copy: 'Jump off',
    choice1: '16',
    choice2: '15',
  },
  { id:10,
    title: 'The Cliff',
    image1: king,
    image2: cliff,
    image1position: ' col-md-offset-3 col-md-3 top-15',
    image2position: ' col-md-5 col-md-offset-0 top-0',
    copyposition: '  col-md-offset-0  top-0 col-md-4',
    copy: 'Suspicious of this place you’ve found yourself in. You move quietly through the Ceibos until you’re blocked  by a cliff. From behind a tree, someone emerges and signals for you to jump over the cliff. ',
    copy2:'In a fit of emotions and urgency you…',
    button1copy: 'Begin to weep',
    button2copy: 'Push them off',
    choice1: '16',
    choice2: '17',
  },
  { id:11,
    title: 'The Cliff',
    image1: cliff,
    image2: godess,
    image1position: ' col-md-offset-1 col-md-3 top-0',
    image2position: ' col-md-offset-2 col-md-5 top-5"',
    copyposition: '  top-10 col-md-offset-3 col-md-4',
    copy: 'With the earrings securely in hand, you continue forward until you see a figure waving you down on a cliff. You stop and she confidently asks you to jump if you want to save your family. ',
    copy2:'In a fit of emotions and urgency you…',
    button1copy: 'Begin to weep',
    button2copy: 'Jump off',
    choice1: '16',
    choice2: '15',
  },
    { id:12,
      title: 'The Cliff',
      image1: cliff,
      image2: godess,
      image1position: ' col-md-offset-1 col-md-3 top-0',
      image2position: ' col-md-offset-2 col-md-5 top-5"',
      copyposition: '  top-10 col-md-offset-3 col-md-4',
      copy: 'Under a heated sun you reach a cliff, and a woman is waiting there. She waves you down and you feel you have no choice but to stop. Quietly, she says she knows what you’re looking for and all you have to do is jump off to find it.',
      copy2:'In a fit of emotions and urgency you…',
      button1copy: 'Push her off',
      button2copy: 'Begin to weep',
      choice1: '17',
      choice2: '16',
    },
    { id:13,
      title: 'The Cliff',
      image1: cliff,
      image2: godess,
      image1position: ' col-md-offset-1 col-md-3 top-0',
      image2position: ' col-md-offset-2 col-md-5 top-5"',
      copyposition: '  top-10 col-md-offset-3 col-md-4',
      copy: 'You take the earrings and run towards the cliff when a woman appears inviting you to jump the cliff with her, exclaiming that the jewels you are looking for are below. ',
      copy2:'In a fit of emotions and urgency you…',
      button1copy: 'Begin to weep',
      button2copy: 'Push her off',
      choice1: '16',
      choice2: '17',
    },
    { id:14,
      title: 'The Cliff',
      image1: cliff,
      image2: godess,
      image1position: ' col-md-offset-1 col-md-3 top-0',
      image2position: ' col-md-offset-2 col-md-5 top-5"',
      copyposition: '  top-10 col-md-offset-3 col-md-4',
      copy: 'You jump off the horse and watch him ride away. Confused, you walk towards the cliff when a woman suddenly begins walking besides you asking you to jump off the cliff with her. The jewels are below, she says.  ',
      copy2:'In a fit of emotions and urgency you…',
      button1copy: 'Begin to weep',
      button2copy: 'Push her off',
      choice1: '17',
      choice2: '15',
    },
    ///
    { id:15,
      title: 'The Ring',
      image1: lionring,
      image2: shore,
      image1position: ' col-md-offset-4 col-md-5 top-10',
      image2position: ' col-md-2 top-15',
      copyposition: '  col-md-offset-1 col-md-4',
      copy: 'Your stomach dips, but then you float towards a rocky shore. You’re alone now, facing a dark figure. They’re guarding the ring you’ve been looking for.  ',
      copy2:' They turn to look at you, “Why you?”',
      button1copy: 'Offer the earrings',
      button2copy: 'Steal the ring',
      choice1: '19',
      choice2: '20',
    },
    { id:16,
      title: 'The Ring',
      image1: lionring,
      image2: shore,
      image1position: ' col-md-offset-4 col-md-5 top-10',
      image2position: ' col-md-2 top-15',
      copyposition: '  col-md-offset-1 col-md-4',
      copy: 'She takes your hand, close your eyes, and when you open them you’re standing alone at a rocky shore. You look up to see a figure hovering over you. You don’t know how but you know he has the ring.  ',
      button1copy: 'Ask kindly',
      button2copy: 'Offer the earrings',
      choice1: '18',
      choice2: '19',
    },
    { id:17,
      title: 'The Ring',
      image1: lionring,
      image2: shore,
      image1position: ' col-md-offset-4 col-md-5 top-10',
      image2position: ' col-md-2 top-15',
      copyposition: '  col-md-offset-1 col-md-4',
      copy: 'Your strength is more than you expected and you tumble down along with her. You land with a thud, unable to move, the waves crashing against you. A figure walks towards you and you know they have it.  ',
      button1copy: 'Steal it',
      button2copy: 'Ask kindly',
      choice1: '20',
      choice2: '18',
    },
    //
    { id:18,
      title: 'xx The End xx',
      image1: ring,
      image2: godess,
      copyposition: '  col-md-offset-4 col-md-4 top-5',
      image1position: ' col-md-offset-0 col-md-5',
      image2position: ' col-md-offset-2 col-md-4 top-10',
      copy: 'You speak of your family and how they need this ring to stay together. The figures is moved and slowly hands you the ring. As you take the glowing ring, you begin to feel confident and powerful. ',
      copy2:"You’ll stay in BC Valdivia, screw your family. You’ll be a ruler here.",
      button1copy: 'Play again',
      button2copy: 'Share this',
      choice1: '0',
      choice2: '0',
    },
    { id:19,
      title: 'xx The End xx',
      image1: ring-helper,
      image2: shore,
      copyposition: '  col-md-offset-4 col-md-4 top-5',
      image1position: ' col-md-offset-0 col-md-5',
      image2position: ' col-md-offset-2 col-md-4 top-10',
      copy: 'Unfortunately, trade systems don’t yet exist in BC Valdivia, and the figure is offended and disappears. ',
      copy2:"You’re left on the shore,  your family at risk of falling apart. ",
      button1copy: 'Play again',
      button2copy: 'Share this',
      choice1: '0',
      choice2: '0',
    },
    { id:20,
      title: 'xx The End xx',
      image1: ring,
      image2: shore,
      copyposition: '  col-md-offset-4 col-md-4 top-5',
      image1position: ' col-md-offset-0 col-md-5',
      image2position: ' col-md-offset-2 col-md-4 top-10',
      copy: 'With unexpected agility you grab the ring and push the figure to the sea. You hold it tightly in your closed fist, the glow peeking through.  ',
      copy2:"Your family is going to make it. ",
      button1copy: 'Play again',
      button2copy: 'Share this',
      choice1: '0',
      choice2: '0',
    },
];

export default Content;
