
import woman from './pic-collage/woman.jpg';
import womanmap from './pic-collage/woman-map.jpg';
import map from './pic-collage/map2.jpg';
import margarita from './pic-collage/margarita.jpg';
import bosque from './pic-collage/bosque1.jpg';
import bosque2 from './pic-collage/bosque2.jpg';
import pescadores from './pic-collage/pescadores.jpg';
import cowboy from './pic-collage/cowboy.jpg';
import ncowboy from './pic-collage/no-cowboy.jpg';
import godess from './pic-collage/godess.jpg';
import helperbg from './pic-collage/helper-bg.jpg';
import helper from './pic-collage/helper.jpg';
import lionring from './pic-collage/lion-ring.jpg';
import map2 from './pic-collage/map2.jpg';
import ringhelper from './pic-collage/ring-helper.jpg';
import ring from './pic-collage/ring.jpg';
import earrings from './pic-collage/earrings.jpg';
import cliff from './pic-collage/cliff2.jpeg';
import ceibo from './pic-collage/ceibo.jpg';
import king from './pic-collage/king.jpg';
import shore from './pic-collage/rocky-shore2.jpg';
import shore2 from './pic-collage/shore2.jpg';
import cliff2 from './pic-collage/cliff2.jpg';



const Content = [
  { id:0,
    title: 'xx The Mission xx',
    image1: bosque,
    image2: woman,
    copyposition: '  col-md-offset-4 col-md-4 top-5',
    image1position: ' col-md-offset-1 col-md-4',
    image2position: ' col-md-offset-2 col-md-4 top-10',
    copy: 'Your family is at risk of falling apart. You have 24 hours to save them, by finding your ancestors golden ring.',
    copy2:'You wake up on a hard ground, under a beating sun. Quickly, you get up and...',
    button1copy:"explore",
    button2copy:"get help",
    choice1:1,
    choice2:2,
  },
    /// A
  { id:1, // Explore
    title: 'The Land',
    image1: map,
    image2: pescadores,
    image1position: ' col-md-offset-1 col-md-6 top-5',
    image2position: ' col-md-offset-0 col-md-2 top-1',
    copyposition: '  col-md-offset-6 col-md-4 top-15',
    copy: 'You begin runnning; past dry forests, fishermen who try and wave you down, and villages in the shape of horseshoes.',
    copy2:' Finally, you reach the shore and stop for a break. On the horizon, a figure slowly emerges.',
    button1copy:"Meet them",
    button2copy:"Hide",
    choice1:3,
    choice2:4,
  },
  { id:2, // Get help
    title: 'The Cowboy',
    image1: bosque2,
    image2: cowboy,
    image1position: ' col-md-offset-1 col-md-3 top-20',
    image2position: ' col-md-6 top-0',
    copyposition: '  col-md-offset-2 col-md-4 top-10',
    copy: 'You call out and at first you hear only hummingbirds, but a few minutes later, a cowboy rushes out of the dry forest.',
    copy2:'He gallops to your feet, “Amiga, I can help you and your family."',
    button1copy:"Kick him",
    button2copy:"Jump on",
    choice1:5,
    choice2:6,
  },
    /// B - Helper
    { id:3, // Meet them
      title: 'The Amiga',
      image1: helper,
      image2: earrings,
      image1position: ' col-md-offset-0 col-md-5 top-0',
      image2position: ' col-md-offset-0 col-md-3 top-20',
      copyposition: '  col-md-offset-7 top-0 col-md-4',
      copy: 'You approach them cautiously, and notice their clay colored skin and smooth black hair. “Amiga, I\'ll take you to the ring.”, they whisper.',
      copy2:'They extend their hand to reveal a pair of sparkling earrings, “Trust me”. You reach your arm out and...',
      button1copy:"Accept them",
      button2copy:"Knock them down",
      choice1:7,
      choice2:8,
    },
    { id:4, // Hiding
      title: 'The Earrings',
      image1: ceibo,
      image2: earrings,
      image1position: ' col-md-offset-0 col-md-3 top-5',
      image2position: ' col-md-offset-3 col-md-5 top-0',
      copyposition: '  col-md-offset-2 col-md-4 top-10',
      copy: 'You run away from the shore back to the forest, but something on the ground catches your eye. ',
      copy2:'It\'s a pair of beautiful silver earrings, you hesitate for a moment and then you...',
      choice1:9,
      choice2:10,
      button1copy:"Pocket them",
      button2copy:"Keep running",
    },
    /// B - Cowboy
    { id:5, // Kick him
      title: 'The earrings',
      image1: ncowboy,
      image2: womanmap,
      image1position: ' col-md-offset-3 col-md-4 top-10',
      image2position: ' col-md-4 top-10',
      copyposition: '  col-md-offset-1 col-md-4 top-5',
      copy: 'He falls to the ground, and you jump on the horse and ride away. You pass fishermen and horseshoe shaped villages, until a woman signals you to stop. ',
      copy2:'She\'s never seen a woman on a horse before, feeling moved, she offers you a pair of silver earrings. You gratiously...',
      button1copy: 'Decline',
      button2copy: 'Accept',
      choice1: '11',
      choice2: '12',
    },
    { id:6, // Jump on
      title: 'The earrings',
      image1: cliff,
      image2: earrings,
      image1position: ' col-md-offset-0 col-md-3 top-20',
      image2position: ' col-md-offset-2 col-md-5 top-10',
      copyposition: '  col-md-offset-2 col-md-4 top-5',
      copy: 'You ride away with the cowboy, past fishermen and horeshoe shaped villages until you come to the edge a cliff.',
      copy2:'He turns to you and timidly asks you to stay as his wife, and offers up a pair of silver earrings. You hesitate and then...',
      button1copy: 'Steal the jewels',
      button2copy: 'Reject him',
      choice1: '13',
      choice2: '14',
    },
  //
  { id:7, // Accept them from caoba
    title: 'The Cliff',
    image1: godess,
    image2: cliff,
    image1position: ' col-md-offset-0 col-md-5 top-0',
    image2position: ' col-md-offset-2 col-md-3 top-5"',
    copyposition: '  top-10 col-md-offset-5 col-md-4',
    copy: 'Earrings dangling, you walk through dry terrains while Caoba holds your hand. You reach a cliff where they stop and softly ask you to jump with them. ',
    copy2:'In a fit of emotions and urgency you…',
    button1copy: 'Jump',
    button2copy: 'Collapse & cry',
    choice1: '15',
    choice2: '17',
  },
  { id:8, // Reject caobas hand...
    title: 'The Cliff',
    image1: cliff2,
    image2: godess,
    image1position: ' col-md-offset-3 col-md-4 top-5',
    image2position: ' pic-item col-md-4 top-10',
    copyposition: '  top-10 col-md-offset-1 col-md-4',
    copy: '“You’ll regret that”, they say, before disappearing into a dry forest. Under a piercing sun, you wander until you reach a cliff. Silently, a figure appears beside you. ',
    copy2:'In a fit of emotions and urgency you…',
    button1copy: 'Collapse & cry',
    button2copy: 'Push them off',
    choice1: '16',
    choice2: '17',
  },
  { id:9, // Take the earrings from the ground
    title: 'The Cliff',
    image1: cliff,
    image2: king,
    image1position: ' col-md-offset-3 col-md-3 top-15',
    image2position: ' col-md-5 col-md-offset-0 top-0',
    copyposition: '  col-md-offset-0  top-0 col-md-4',
    copy: 'Earrings dangling, you wander calmly until you you reach a cliff. From behind a tree, someone emerges and whispers in your ear: jump with me. ',
    copy2:'In a fit of emotions and urgency you…',
    button1copy: 'Collapse & cry',
    button2copy: 'Jump',
    choice1: '16',
    choice2: '15',
  },
  { id:10, // keep running don't pick up the earrrings
    title: 'The Cliff',
    image1: king,
    image2: cliff2,
    image1position: ' col-md-offset-3 col-md-4 top-10',
    image2position: ' col-md-4 col-md-offset-1 top-0',
    copyposition: '  col-md-offset-0  top-0 col-md-4',
    copy: 'Suspicious of everything around you, you move quietly through a dry forest until you’re blocked by a cliff. From behind a tree, someone emerges and signals for you to jump over the cliff.',
    copy2:'In a fit of emotions and urgency you…',
    button1copy: 'Collapse & cry',
    button2copy: 'Push them off',
    choice1: '16',
    choice2: '17',
  },
  { id:11,
    title: 'The Cliff',
    image1: cliff,
    image2: godess,
    image1position: ' col-md-offset-1 col-md-3 top-0',
    image2position: ' col-md-offset-2 col-md-5 top-5"',
    copyposition: '  top-10 col-md-offset-3 col-md-4',
    copy: 'She tucks them in your boots anyways and you continue forward until you reach a cliff where a figure waves you down. They ask you to jump if you want to save your family. ',
    copy2:'In a fit of emotions and urgency you…',
    button1copy: 'Colapse & cry',
    button2copy: 'Jump off',
    choice1: '16',
    choice2: '15',
  },
    { id:12,
      title: 'The Cliff',
      image1: cliff2,
      image2: godess,
      image1position: ' col-md-offset-1 col-md-3 top-0',
      image2position: ' col-md-offset-2 col-md-5 top-5"',
      copyposition: '  top-10 col-md-offset-3 col-md-4',
      copy: 'You continue riding, earrings dangling, until you come to a path blocked by a cliff. You see a figure standing on the edge. They look back at you and signal you to jump.',
      copy2:'In a fit of emotions and urgency you…',
      button1copy: 'Push them off',
      button2copy: 'Jump off',
      choice1: '17',
      choice2: '15',
    },
    { id:13,
      title: 'The Cliff',
      image1: cliff,
      image2: godess,
      image1position: ' col-md-offset-1 col-md-3 top-0',
      image2position: ' col-md-offset-2 col-md-5 top-5"',
      copyposition: '  top-10 col-md-offset-3 col-md-4',
      copy: 'You grab the earrings and rush towards the cliff, unsure of what your plan is. Suddenly a figure appears, and they signal for you to jump over the cliff with them..',
      copy2:'Feeling stuck and overwhelmed you...',
      button1copy: 'Jump off',
      button2copy: 'Push them off',
      choice1: '15',
      choice2: '17',
    },
    { id:14,
      title: 'The Cliff',
      image1: cliff2,
      image2: godess,
      image1position: ' col-md-offset-1 col-md-3 top-0',
      image2position: ' col-md-offset-2 col-md-5 top-5"',
      copyposition: '  top-10 col-md-offset-3 col-md-4',
      copy: 'You jump off the horse and watch him ride away. Confused, you walk towards the cliff to look below. You notice someone at the edge of the cliff, and walk towards them. ',
      copy2:'In a fit of emotions and urgency you…',
      button1copy: 'Collapse & cry',
      button2copy: 'Push them off',
      choice1: '16',
      choice2: '17',
    },
    /// jump off
    { id:15,
      title: 'The Ring',
      image1: lionring,
      image2: shore,
      image1position: ' col-md-offset-4 col-md-5 top-10',
      image2position: ' col-md-2 top-15',
      copyposition: '  col-md-offset-1 col-md-4',
      copy: 'You prepare for the worst, but soon you\'re floating neatly down to the shore. Once on shore, your partner extends their hand to reveal the ring.',
      copy2:' "Why should I give you the ring?" they ask.” With a deep sense of confidence, you... ',
      button1copy: 'Offer the earrings',
      button2copy: 'Steal the ring',
      choice1: '19',
      choice2: '20',
    }, //begin to weep
    { id:16,
      title: 'The Ring',
      image1: lionring,
      image2: shore,
      image1position: ' col-md-offset-4 col-md-5 top-10',
      image2position: ' col-md-2 top-15',
      copyposition: '  col-md-offset-1 col-md-4',
      copy: 'With their fingertips they lightly close your eyes. You open them to find yourself at a rocky shore, with the figure standing by you.',
      copy2:'Why should I give you the ring?" they ask.” With a deep sense of confidence, you... ',
      button1copy: 'Ask kindly',
      button2copy: 'Offer the earrings',
      choice1: '18',
      choice2: '19',
    }, // push her off
    { id:17,
      title: 'The Ring',
      image1: lionring,
      image2: shore,
      image1position: ' col-md-offset-4 col-md-5 top-10',
      image2position: ' col-md-2 top-15',
      copyposition: '  col-md-offset-1 col-md-4',
      copy: 'You\'re stronger than you thought and you tumble down along with them.You land with a thud, unable to move, the waves crashing against you.',
      copy2:'"Why should I give you the ring?" they ask.” With a deep sense of confidence, you...',
      button1copy: 'Steal it',
      button2copy: 'Ask kindly',
      choice1: '20',
      choice2: '18',
    },
    //ask kindly
    { id:18,
      title: 'xx The End xx',
      image1: ring,
      image2: godess,
      copyposition: '  col-md-offset-4 col-md-4 top-5',
      image1position: ' col-md-offset-0 col-md-5',
      image2position: ' col-md-offset-2 col-md-4 top-10',
      copy: 'You tell them about your hermano, and your niece and how they need this to ring together. Their eyes widen in horror, and hand you the ring. As you take the glowing ring, you begin to feel confident and powerful. ',
      copy2:"You’ll stay in Valdivia, screw your family. You’ll be a ruler here.",

    }, //offer the earrings
    { id:19,
      title: 'xx The End xx',
      image1: lionring,
      image2: shore2,
      copyposition: '  col-md-offset-4 col-md-4 top-5',
      image1position: ' col-md-offset-0 col-md-5',
      image2position: ' col-md-offset-2 col-md-4 top-10',
      copy: 'Unfortunately, trade systems don’t exist here yet. Deeply offended at your offer, they dissapear along with the ring. ',
      copy2:"You’re left alone on the the shore, and you\'re family won\'t make it.' ",


    }, // try and take it
    { id:20,
      title: 'xx The End xx',
      image1: ring,
      image2: shore2,
      copyposition: '  col-md-offset-4 col-md-4 top-5',
      image1position: ' col-md-offset-0 col-md-5',
      image2position: ' col-md-offset-2 col-md-4 top-10',
      copy: 'With unexpected agility you grab the ring and push the figure to the sea. You hold it tightly in your closed fist, the glow peeking through.  ',
      copy2:"Your family is going to stay together ",


    },
];

export default Content;
